//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTRAK
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicsLog
    {
        public int Id { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Picture { get; set; }
        public string Team { get; set; }
        public string DeviceIP { get; set; }
        public Nullable<double> Size { get; set; }
        public string Pickup { get; set; }
        public string Item { get; set; }
        public string Company { get; set; }
    }
}
