//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTRAK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int Qty { get; set; }
        public string Notes { get; set; }
        public int PickupID { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Company { get; set; }
        public Nullable<int> PickupReff { get; set; }
    
        public virtual Pickup Pickup { get; set; }
    }
}
