//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTRAK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pickup
    {
        public Pickup()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        public string LocationName { get; set; }
        public string TransporterName { get; set; }
        public string Rep { get; set; }
        public string Manager { get; set; }
        public string Account { get; set; }
        public string ShipCode { get; set; }
        public string Team { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public string Status { get; set; }
        public string ClosedBy { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> Cancelled { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string Notes { get; set; }
        public int SortOrder { get; set; }
        public string Temp { get; set; }
        public string LastEditBy { get; set; }
        public string Mode { get; set; }
        public string Destination { get; set; }
        public string Company { get; set; }
        public int PickupNumber { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
